version: "3"
services:
  db:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql-server/init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    ports:
      - "13306:3306"
    command: mysqld


volumes:
  db_data:
    driver: local
