// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc_multi_content

import (
	"database/sql"
	"time"
)

type User struct {
	ID int64 `db:"id"`
	// 名前
	Name string `db:"name"`
	// ニックネーム
	Nickname  sql.NullString `db:"nickname"`
	CreatedAt time.Time      `db:"created_at"`
	UpdatedAt time.Time      `db:"updated_at"`
}
