// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package model_content

import (
	"time"
)

type Content struct {
	ID        int64     `db:"id"`
	UserID    int64     `db:"user_id"`
	Content   string    `db:"content"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}
